#pragma once

#include <cilantro/accumulators.hpp>
#include <cilantro/colormap.hpp>
#include <cilantro/connected_component_segmentation.hpp>
#include <cilantro/convex_hull_utilities.hpp>
#include <cilantro/convex_polytope.hpp>
#include <cilantro/correspondence.hpp>
#include <cilantro/data_containers.hpp>
#include <cilantro/flat_convex_hull_3d.hpp>
#include <cilantro/grid_accumulator.hpp>
#include <cilantro/grid_downsampler.hpp>
#include <cilantro/icp_base.hpp>
#include <cilantro/icp_rigid_combined_metric_3d.hpp>
#include <cilantro/icp_rigid_point_to_point.hpp>
#include <cilantro/icp_simple_feature_adaptors.hpp>
#include <cilantro/image_point_cloud_conversions.hpp>
#include <cilantro/image_viewer.hpp>
#include <cilantro/io.hpp>
#include <cilantro/kd_tree.hpp>
#include <cilantro/kmeans.hpp>
#include <cilantro/mean_shift.hpp>
#include <cilantro/multidimensional_scaling.hpp>
#include <cilantro/nearest_neighbor_graph.hpp>
#include <cilantro/normal_estimation.hpp>
#include <cilantro/plane_estimator.hpp>
#include <cilantro/point_cloud.hpp>
#include <cilantro/principal_component_analysis.hpp>
#include <cilantro/random_sample_consensus.hpp>
#include <cilantro/renderables.hpp>
#include <cilantro/rigid_registration_utilities.hpp>
#include <cilantro/rigid_transform_estimator.hpp>
#include <cilantro/simple_similarity_evaluators.hpp>
#include <cilantro/space_region.hpp>
#include <cilantro/space_transformations.hpp>
#include <cilantro/spectral_clustering.hpp>
#include <cilantro/type_traits.hpp>
#include <cilantro/visualizer.hpp>
#include <cilantro/visualizer_handler.hpp>
