#pragma once

#include <cilantro/accumulators.hpp>
#include <cilantro/colormap.hpp>
#include <cilantro/common_renderables.hpp>
#include <cilantro/common_similarity_evaluators.hpp>
#include <cilantro/connected_component_segmentation.hpp>
#include <cilantro/convex_hull_utilities.hpp>
#include <cilantro/convex_polytope.hpp>
#include <cilantro/correspondence.hpp>
#include <cilantro/data_containers.hpp>
#include <cilantro/flat_convex_hull_3d.hpp>
#include <cilantro/grid_accumulator.hpp>
#include <cilantro/grid_downsampler.hpp>
#include <cilantro/icp_common_feature_adaptors.hpp>
#include <cilantro/icp_common_instances.hpp>
#include <cilantro/icp_core.hpp>
#include <cilantro/icp_correspondence_search_kd_tree.hpp>
#include <cilantro/icp_correspondence_search_projective.hpp>
#include <cilantro/icp_rigid_combined_metric_optimizer_3d.hpp>
#include <cilantro/icp_rigid_point_to_point_metric_optimizer.hpp>
#include <cilantro/image_point_cloud_conversions.hpp>
#include <cilantro/image_viewer.hpp>
#include <cilantro/io.hpp>
#include <cilantro/kd_tree.hpp>
#include <cilantro/kmeans.hpp>
#include <cilantro/mean_shift.hpp>
#include <cilantro/multidimensional_scaling.hpp>
#include <cilantro/nearest_neighbor_graph_utilities.hpp>
#include <cilantro/normal_estimation.hpp>
#include <cilantro/point_cloud.hpp>
#include <cilantro/principal_component_analysis.hpp>
#include <cilantro/ransac_base.hpp>
#include <cilantro/ransac_hyperplane_estimator.hpp>
#include <cilantro/ransac_rigid_transformation_estimator.hpp>
#include <cilantro/renderable.hpp>
#include <cilantro/rigid_registration_utilities.hpp>
#include <cilantro/space_region.hpp>
#include <cilantro/space_transformations.hpp>
#include <cilantro/spectral_clustering.hpp>
#include <cilantro/timer.hpp>
#include <cilantro/visualizer.hpp>
#include <cilantro/visualizer_handler.hpp>
